#!/bin/sh
## bspwm dual monitor config
## Based on miikanissi's config: https://github.com/miikanissi/dotfiles
## For more detailed information, read:
## https://miikanissi.com/blog/hotplug-dual-monitor-setup-bspwm/

RANDR=$(xrandr)
INTERNAL_MONITOR=$(echo "$RANDR" | awk '/ primary/{print $1}')
if [ "$INTERNAL_MONITOR" = "DP-0" ]; then
  # this indicate this machine xorg setting is set using NVIDIA.
  # change internal monitor to eDP-1-1
  INTERNAL_MONITOR="eDP-1-1"
  # set eDP-1-1 as primary monitor
  xrandr --output "$INTERNAL_MONITOR" --primary
fi

EXTERNAL_MONITOR="HDMI-1"

## on first load, setup default workspaces
if [ "$1" = 0 ]; then
  if xrandr -q | grep "${EXTERNAL_MONITOR} connected"; then
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

# Helper function to check for active process,
# if not found starts program on the background.
_run() {
  if ! pgrep -x "${1}" >/dev/null; then
    "$@" &
  fi
}

bspc config border_width            2
bspc config window_gap              6
bspc config top_padding             32

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config single_monocle          true
bspc config focus_follows_pointer   true

bspc config focused_border_color    "#63C5EA"
bspc config active_border_color     "#2BE491"

## Use `xprop | grep WM_CLASS` to see WM class (require `xorg-xprop` package)
bspc rule -a firefox-developer-edition desktop='^2'  follow=on split_ratio=0.35
bspc rule -a TelegramDesktop           desktop='^6'  follow=on split_ratio=0.60
bspc rule -a nheko                     desktop='^6'  follow=on split_ratio=0.40
bspc rule -a "thunderbird":Mail        desktop='^10' follow=on
bspc rule -a "thunderbird":Navigator   desktop='^10' state=floating
bspc rule -a "thunderbird":Msgcompose  desktop='^10' state=floating

bspc rule -a mpv         state=floating

# mouse, cursor, fonts
xsetroot -cursor_name left_ptr &
# xset +fp ~/.fonts &
# xset fp rehash &
# fc-cache -fv &

_run sxhkd -m -1 > /tmp/sxhkd.log

# PCManFM File browser daemon 
_run pcmanfm -d

# Network Manager applet
_run nm-applet

# Compositor, If you want to run one, execute here
# _run picom

# Setup monitors, polybar and wallpaper
~/.config/bspwm/scripts/bspwm_setup_monitors.sh &

# vim: set ts=2 sw=2 et:
