#!/bin/sh
#
# Bspwm dual monitor config
#
# This bspwmrc script based on miikanissi's bspwmrc file:
# https://github.com/miikanissi/dotfiles
# For more detailed information, read:
# https://miikanissi.com/blog/hotplug-dual-monitor-setup-bspwm/

# RANDR=$(xrandr)
# INTERN=$(echo "$RANDR" | awk '/ primary/{print $1}')
# if [ "$INTERN" = "DP-0" ]; then
#   # this indicate this machine xorg setting is set using NVIDIA.
#   # change internal monitor to eDP-1-1
#   INTERN="eDP-1-1"
#   # set eDP-1-1 as primary monitor
#   xrandr --output "$INTERN" --primary
# fi

INTERN="eDP-1-1"
xrandr --output "$INTERN" --primary

# Specific for this machine:
# HDMI Port = DP-1
# MiniDP = DP-3
# MiniDP 1.2 = DP-3.8
EXTERN="DP-3"

## on first load, setup default workspaces
if [ "$1" = 0 ]; then
  if xrandr -q | grep "${EXTERN} connected"; then
    bspc monitor "$INTERN" -d 1 2 3 4 5 6
    bspc monitor "$EXTERN" -d 7 8 9 10 11 12
    bspc wm -O "$INTERN" "$EXTERN"
  else
    bspc monitor "$INTERN" -d 1 2 3 4 5 6 7 8 9 10 11 12
  fi
fi

# helper function to check for active process, if process not found,
# starts program on the background.
_run() {
  if ! pgrep -x "${1}" >/dev/null; then
    "$@" &
  fi
}

bspc config border_width            2
bspc config window_gap              6
bspc config top_padding             32

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config single_monocle          true
bspc config focus_follows_pointer   true

bspc config focused_border_color    "#89b4fa"
bspc config active_border_color     "#f9e2af"

## Use `xprop | grep WM_CLASS` to see WM class (require `xorg-xprop` package)
bspc rule -a Chromium                  desktop='^2'  follow=on
bspc rule -a firefox-developer-edition desktop='^8'  follow=on
bspc rule -a TelegramDesktop           desktop='^6'  follow=on split_ratio=0.60
bspc rule -a nheko                     desktop='^6'  follow=on split_ratio=0.40
bspc rule -a Gimp-3.0                  desktop='^9'  follow=on
bspc rule -a "thunderbird":Mail        desktop='^12' follow=on
bspc rule -a "thunderbird":Navigator   desktop='^12' state=floating
bspc rule -a "thunderbird":Msgcompose  desktop='^12' state=floating

bspc rule -a KeePassXC   state=floating
bspc rule -a mpv         state=floating
bspc rule -a feh         state=floating

# mouse, cursor, fonts
xsetroot -cursor_name left_ptr &
# xset +fp ~/.fonts &
# xset fp rehash &
# fc-cache -fv &

_run sxhkd -m -1 > /tmp/sxhkd.log

# PCManFM File browser daemon 
_run prime-run pcmanfm -d

# Network Manager applet
_run nm-applet

# Compositor, If you want to run one, execute here
# _run picom

# Setup monitors, polybar and wallpaper
~/.config/bspwm/scripts/bspwm_setup_monitors.sh &

# vim: set ts=2 sw=2 et:
