#!/bin/sh

userresources=$HOME/.config/X11/.Xresources
usermodmap=$HOME/.config/X11/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr --auto

# By default, Xorg always sets DPI to 96. To acquire the real/preferred/native
# PPI/DPI of connected monitors, you can use CMCDragonkai's bash script:
# https://gist.github.com/CMCDragonkai/74585d00b6a1a6fb9292
xrandr --dpi 141

# NVIDIA graphics
# xrandr --setprovideroutputsource modesetting NVIDIA-0

# Keyboard rate speed and delay
xset r rate 250 30
xbindkeys -f "$XDG_CONFIG_HOME/xbindkeys/config"

eval $(ssh-agent)

exec bspwm
