#!/bin/sh
## Dual Monitor Auto Detect
## Based on miikanissi config.
## https://github.com/miikanissi/dotfiles
## Please read https://miikanissi.com/blog/hotplug-dual-monitor-setup-bspwm/
## for more information.

INTERNAL_MONITOR="LVDS-1"
EXTERNAL_MONITOR="VGA-1"

## on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi
## End dual monitor auto detect

## AUTOSTART
## Helper function to check for active process, if not found starts program on the background
_run() {
    if ! pgrep -x "${1}" &>/dev/null; then
        "$@" &
    fi
}

bspc config border_width         2
bspc config window_gap           6
bspc config top_padding          32

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config single_monocle          true
bspc config focus_follows_pointer   true

bspc config focused_border_color      "#63C5EA"
bspc config active_border_color       "#2BE491"

## Use `xprop | grep WM_CLASS` to see WM class (require `xorg-prop` package)
bspc rule -a Gimp-2.10          desktop='^8'  state=floating follow=on
bspc rule -a TelegramDesktop    desktop='^5'                 follow=on   split_ratio=0.65                    
bspc rule -a Element            desktop='^5'                 follow=on   split_ratio=0.35
bspc rule -a Chromium           desktop='^9'
bspc rule -a Chromium-browser   desktop='^10'
bspc rule -a Brave-browser      desktop='^2'
#bspc rule -a Pcmanfm                         state=floating
bspc rule -a Galculator                       state=floating
bspc rule -a mplayer2                         state=floating
bspc rule -a Gpicview                         state=floating
bspc rule -a XpdfReader                       state=floating
bspc rule -a Kupfer.py                                       focus=on
bspc rule -a Screenkey                                       manage=off
bspc rule -a 'Brave-browser:brave-browser (./Dat/Igno)'      desktop='^10'

## mouse, cursor, fonts
xsetroot -cursor_name left_ptr &
#xset +fp ~/.fonts &
#xset fp rehash &
#fc-cache -fv &


_run sxhkd -m -1 > /tmp/sxhkd.log

## PCManFM File browser daemon 
_run pcmanfm -d

## Music daemon
_run mpd

## Network Manager applet
_run nm-applet

## Compositor
## No, I don't use compositor
## If you want to run one, execute here
##_run picom

# URXVT Daemon
_run urxvtd -q &

# Setup monitors, polybar and wallpaper
~/.config/bspwm/scripts/bspwm_setup_monitors.sh &
